title: Karina Gesmundo
author: Karina Gesmundo
email: gesmundokarina@gmail.com
description: "this is my website/CV/blog"

# social links
twitter_username: your-twitter-handle
github_username:  kgesmundo

show_excerpts: true # set to false to remove excerpts on the homepage

#theme: minima
